######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : split, Index = 0, Count = 1
# SUBMIT FILE NAME : register_local-hcc_2_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=78a8c959-651f-476b-b2ff-86f753ab1c88 PEGASUS_WF_LABEL=split PEGASUS_DAG_JOB_ID=register_local-hcc_2_0 PEGASUS_SITE=local"
arguments = " -n pegasus::rc-client -N null -R local  -L split -T 2020-02-06T20:24:34-06:00 /usr/bin/pegasus-rc-client --conf /work/csesd/pnnguyen/plant-phenotyping/pics2predictions/submit/pnnguyen/pegasus/split/20200206T202520-0600/pegasus.5688879069993397762.properties -v --insert /work/csesd/pnnguyen/plant-phenotyping/pics2predictions/submit/pnnguyen/pegasus/split/20200206T202520-0600/00/00/register_local-hcc_2_0.in"
error = /work/csesd/pnnguyen/plant-phenotyping/pics2predictions/submit/pnnguyen/pegasus/split/20200206T202520-0600//00/00/register_local-hcc_2_0.err
executable = /usr/bin/../bin/pegasus-kickstart
log = /work/csesd/pnnguyen/plant-phenotyping/pics2predictions/submit/pnnguyen/pegasus/split/20200206T202520-0600/split-0.log
notification = NEVER
output = /work/csesd/pnnguyen/plant-phenotyping/pics2predictions/submit/pnnguyen/pegasus/split/20200206T202520-0600//00/00/register_local-hcc_2_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 50
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "78a8c959-651f-476b-b2ff-86f753ab1c88"
+pegasus_wf_uuid = "78a8c959-651f-476b-b2ff-86f753ab1c88"
+pegasus_version = "4.9.2dev"
+pegasus_wf_name = "split-0"
+pegasus_wf_time = "20200206T202520-0600"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local-hcc_2_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
