######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : split, Index = 0, Count = 1
# SUBMIT FILE NAME : stage_out_local_local-hcc_3_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=78a8c959-651f-476b-b2ff-86f753ab1c88 PEGASUS_WF_LABEL=split PEGASUS_DAG_JOB_ID=stage_out_local_local-hcc_3_0 PEGASUS_SITE=local _PEGASUS_TRANSFER_INPUT_FILES=/work/csesd/pnnguyen/plant-phenotyping/pics2predictions/submit/pnnguyen/pegasus/split/20200206T202520-0600/00/00/python3_ID0000006.meta,/work/csesd/pnnguyen/plant-phenotyping/pics2predictions/submit/pnnguyen/pegasus/split/20200206T202520-0600/00/00/python3_ID0000008.meta, PEGASUS_BIN_DIR=/usr/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "/usr/bin/../bin/pegasus-kickstart  -n pegasus::transfer -N null -i - -R local  -L split -T 2020-02-06T20:24:34-06:00 /usr/bin/../bin/pegasus-transfer  --threads 2 "
error = /work/csesd/pnnguyen/plant-phenotyping/pics2predictions/submit/pnnguyen/pegasus/split/20200206T202520-0600//00/00/stage_out_local_local-hcc_3_0.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
input = /work/csesd/pnnguyen/plant-phenotyping/pics2predictions/submit/pnnguyen/pegasus/split/20200206T202520-0600//00/00/stage_out_local_local-hcc_3_0.in
log = /work/csesd/pnnguyen/plant-phenotyping/pics2predictions/submit/pnnguyen/pegasus/split/20200206T202520-0600/split-0.log
notification = NEVER
output = /work/csesd/pnnguyen/plant-phenotyping/pics2predictions/submit/pnnguyen/pegasus/split/20200206T202520-0600//00/00/stage_out_local_local-hcc_3_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 900
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "78a8c959-651f-476b-b2ff-86f753ab1c88"
+pegasus_wf_uuid = "78a8c959-651f-476b-b2ff-86f753ab1c88"
+pegasus_version = "4.9.2dev"
+pegasus_wf_name = "split-0"
+pegasus_wf_time = "20200206T202520-0600"
+pegasus_wf_xformation = "pegasus::transfer"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "stage_out_local_local-hcc_3_0"
+pegasus_job_class = 3
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
