######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : split, Index = 0, Count = 1
# SUBMIT FILE NAME : python3_ID0000006.sub
######################################################################
stream_error  = false
stream_output = false
environment = ""
+remote_cerequirements = JOBNAME=="python3ID000000" && PASSENV==1 && PRIORITY==20
+remote_environment = "PEGASUS_HOME=/usr CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=89a6f84b-a72c-431e-ba3b-e419006256ad PEGASUS_WF_LABEL=split PEGASUS_DAG_JOB_ID=python3_ID0000006 PEGASUS_SITE=local-hcc PEGASUS_SCRATCH_DIR=/work/csesd/pnnguyen/pics2predictions/scratch/pnnguyen/pegasus/split/20191114T091938-0600 PEGASUS_QUEUE=batch,tmp_anvil"
arguments =  -n python3 -N ID0000006 -o model_4_300_3.8-1-18-corn_33-CH9_2018-08-22_01-43-49_783900.prd.png -R local-hcc  -w /work/csesd/pnnguyen/pics2predictions/scratch/pnnguyen/pegasus/split/20191114T091938-0600  -s model_4_300_3.8-1-18-corn_33-CH9_2018-08-22_01-43-49_783900.prd.png=model_4_300_3.8-1-18-corn_33-CH9_2018-08-22_01-43-49_783900.prd.png -L split -T 2019-11-14T09:19:32-06:00 /work/csesd/pnnguyen/pics2predictions/scripts/run_python.sh -m schnablelab.CNN.Predict_snn Predict model_4_300_3.40421104694053e-05.h5 8-1-18-corn_33-CH9_2018-08-22_01-43-49_783900.npy
batch_queue = batch,tmp_anvil
error = /work/csesd/pnnguyen/pics2predictions/submit/pnnguyen/pegasus/split/20191114T091938-0600//00/00/python3_ID0000006.err
executable = /usr/bin/pegasus-kickstart
grid_resource = batch slurm
log = /work/csesd/pnnguyen/pics2predictions/submit/pnnguyen/pegasus/split/20191114T091938-0600/split-0.log
notification = NEVER
output = /work/csesd/pnnguyen/pics2predictions/submit/pnnguyen/pegasus/split/20191114T091938-0600//00/00/python3_ID0000006.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
request_memory = ifthenelse(isundefined(DAGNodeRetry) || DAGNodeRetry == 0, 4000, 6000)
submit_event_user_notes = pool:local-hcc
transfer_executable = false
universe = grid
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "89a6f84b-a72c-431e-ba3b-e419006256ad"
+pegasus_wf_uuid = "89a6f84b-a72c-431e-ba3b-e419006256ad"
+pegasus_version = "4.9.2dev"
+pegasus_wf_name = "split-0"
+pegasus_wf_time = "20191114T091938-0600"
+pegasus_wf_xformation = "python3"
+pegasus_wf_dax_job_id = "ID0000006"
+pegasus_wf_dag_job_id = "python3_ID0000006"
+pegasus_job_class = 1
+pegasus_site = "local-hcc"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
